version: '3.1'
services:

  wiremock:
    image: wiremock/wiremock
    networks:
    - hmpps_int
    container_name: wiremock_test
    restart: always
    ports:
      - "9999:8080"

networks:
  hmpps_int:
