---
# Per environment values which override defaults in hmpps-community-accommodation-tier-2-bail-ui/values.yaml

generic-service:
  ingress:
    host: community-accommodation-tier-2-bail.hmpps.service.justice.gov.uk
    tlsSecretName: hmpps-community-accommodation-tier-2-bail-cert

  env:
    INGRESS_URL: "https://community-accommodation-tier-2-bail-ui.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    APPROVED_PREMISES_API_URL: "https://approved-premises-api-prod.hmpps.service.justice.gov.uk"
    COMMUNITY_ACCOMMODATION_API_TIMEOUT_RESPONSE: 30000
    COMMUNITY_ACCOMMODATION_API_TIMEOUT_DEADLINE: 30000
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: hmpps-approved-premises
