---
# Per environment values which override defaults in hmpps-community-accommodation-tier-2-bail-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: community-accommodation-tier-2-bail-preprod.hmpps.service.justice.gov.uk
    tlsSecretName: hmpps-community-accommodation-tier-2-bail-preprod-cert

  env:
    INGRESS_URL: "https://community-accommodation-tier-2-bail-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    APPROVED_PREMISES_API_URL: "https://approved-premises-api-preprod.hmpps.service.justice.gov.uk"
    COMMUNITY_ACCOMMODATION_API_TIMEOUT_RESPONSE: 30000
    COMMUNITY_ACCOMMODATION_API_TIMEOUT_DEADLINE: 30000
    ENVIRONMENT_NAME: PRE-PRODUCTION
    AUDIT_ENABLED: "false"

  namespace-secrets:
    hmpps-community-accommodation-tier-2-bail-ui-client-creds:
      CLIENT_CREDS_CLIENT_ID: 'CLIENT_CREDS_CLIENT_ID'
      CLIENT_CREDS_CLIENT_SECRET: 'CLIENT_CREDS_CLIENT_SECRET'

generic-prometheus-alerts:
  alertSeverity: hmpps-approved-premises
