name: Deploy to environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        type: choice
        required: true
        options:
          - dev
          - test
          - preprod
          - prod
        default: 'dev'
      version:
        description: version to be deployed to the environment - must already exist.
        required: true
        default: ''
        type: string

permissions:
  contents: read

jobs:
  helm_lint:
    name: helm lint
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/test_helm_lint.yml@24d1df5c3dce9e4e26fa204dc9149aee0772c2e9 # v2.14.9
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
  deploy_env:
    name: Deploy to environment
    needs:
      - helm_lint
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@24d1df5c3dce9e4e26fa204dc9149aee0772c2e9 # v2.14.9
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
      app_version: ${{ inputs.version }}
